[package]
name = "coolslides_core"
version = "0.1.0"
edition = "2021"
description = "Core types, schema validation, and import map resolution for Coolslides"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }