# Math plugin demo

modelVersion = "1.0"
id = "math-demo"

[component]
name = "TwoColSlide"
versionReq = "^1"

[props]
title = "Math Rendering"
leftWidth = "55%"
rightWidth = "45%"

[slots.left]
kind = "markdown"
value = '''
### Inline Math

Euler's identity: $e^{i\pi} + 1 = 0$  
Quadratic formula: $x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$

### Display Math

$$
\int_0^1 x^2\,dx = \left[\tfrac{x^3}{3}\right]_0^1 = \tfrac{1}{3}
$$

KaTeX is used when available; otherwise a readable fallback is shown.
'''

[slots.right]
kind = "markdown"
value = '''
### Notes

- This deck has the math plugin enabled in `slides.toml`.
- Sanitization allows math when not in strict mode.
- Works in dev and export.
'''
