# Intro Slide

modelVersion = "1.0"
id = "intro"

[component]
name = "TitleSlide"
versionReq = "^1"

[props]
title = "Welcome to Coolslides (Svelte CE)"
# subtitle = "Optional subtitle here"
# alignment = "center"  # left|center|right

