# Quote Slide Example

modelVersion = "1.0"
id = "quote-example"

[component]
name = "QuoteSlide"
versionReq = "^1"

[props]
quote = "I don't care much for powerpoint. So I made this."
author = "Riley Leff"
attribution = "Nitpicky Guy"
style = "default"

[styleOverrides]
"--quote-color" = "#333333"
"--accent-color" = "#007acc"