# Coolslides Example Deck Manifest

modelVersion = "1.0"
title = "Coolslides Example Presentation"
theme = "themes/default/theme.css"
tokens = "themes/default/tokens.css"

plugins = []

[transitions]
default = "slide"

[[sequence]]
type = "ref"
ref = "intro"

[[sequence]]
type = "ref"
ref = "features"

[[sequence]]
type = "ref"
ref = "quote-example"

[[sequence]]
type = "ref"
ref = "poll-demo"

[notes]
intro = "Welcome to Coolslides! This is an example presentation showcasing the basic components."
features = "Here we demonstrate the two-column layout with some key features."
quote-example = "A beautiful quote slide to demonstrate the quote component."
poll-demo = "Dynamic slot demo: Poll widget loads when visible."
